image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
  - yarn install
  - yarn lint
  - yarn test

build:
  stage: build
  script:
  - yarn install
  - yarn build
  artifacts:
    name: "vd-$CI_COMMIT_REF_NAME"
    paths:
    - web-ext-artifacts/*.zip
    expire_in: 1 week

